collections:
  - name: "entries"
    label: "Meditation Entries"
    file: "meditation/data/entries.json"
    format: "json"
    fields:
      - label: "Entries"
        name: "entries"
        widget: "list"
        fields:
          - { label: "Date", name: "date", widget: "date" }
          - { label: "Duration (min)", name: "duration", widget: "number", value_type: "int", min: 1 }
          - { label: "Notes", name: "notes", widget: "text", required: false }
