backend:
  name: github
  repo: bsanghera/SangheraCircuitsWebsite
  branch: main
  base_url: https://late-cell-3508.bsanghera27.workers.dev
  auth_endpoint: /auth

media_folder: "meditation/uploads"
public_folder: "/meditation/uploads"

collections:
  # 1) Folder-based collection: one JSON file per entry
  - name: entries
    label: Meditation Entries
    folder: meditation/data/entries
    create: true
    extension: json
    format: json
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - { label: Date, name: date, widget: date }
      - { label: "Duration (min)", name: duration, widget: number, value_type: int, min: 1 }
      - { label: Notes, name: notes, widget: text, required: false }

  # 2) Files-based collection: single JSON file for takeaways
  - name: takeaways
    label: Key Takeaways
    files:
      - label: Takeaways
        name: takeaways
        file: meditation/data/takeaways.json
        fields:
          - label: Items
            name: items
            widget: list
            field:
              label: Takeaway
              name: item
              widget: string

  # 3) Files-based collection: single JSON file listing entry filenames
  - name: entries_index
    label: Entries Index
    files:
      - label: Index
        name: index
        file: meditation/data/entries/index.json
        fields:
          - label: Files
            name: files
            widget: list
            field:
              label: "Filename (YYYY-MM-DD.json)"
              name: file
              widget: string
